package com.mock.fb.model;

import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

// Generated Jun 2, 2015 9:17:34 AM by Hibernate Tools 4.3.1

/**
 * Friends generated by hbm2java
 */
@XmlRootElement
public class Friends implements java.io.Serializable {

	private Integer id;
	private User userByUserId;
	private User userByFriendId;
	private boolean accept;
	private boolean dealtWith;
	private boolean ignored;

	public Friends() {
	}

	public Friends(User userByUserId, User userByFriendId, boolean accept,
			boolean dealtWith, boolean ignored) {
		this.userByUserId = userByUserId;
		this.userByFriendId = userByFriendId;
		this.accept = accept;
		this.dealtWith = dealtWith;
		this.ignored = ignored;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@XmlTransient
	public User getUserByUserId() {
		return this.userByUserId;
	}

	public void setUserByUserId(User userByUserId) {
		this.userByUserId = userByUserId;
	}

	@XmlTransient
	public User getUserByFriendId() {
		return this.userByFriendId;
	}

	public void setUserByFriendId(User userByFriendId) {
		this.userByFriendId = userByFriendId;
	}

	public boolean isAccept() {
		return this.accept;
	}

	public void setAccept(boolean accept) {
		this.accept = accept;
	}

	public boolean isDealtWith() {
		return this.dealtWith;
	}

	public void setDealtWith(boolean dealtWith) {
		this.dealtWith = dealtWith;
	}

	public boolean isIgnored() {
		return this.ignored;
	}

	public void setIgnored(boolean ignored) {
		this.ignored = ignored;
	}

}
