package com.mock.fb.model;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

// Generated Jun 2, 2015 9:17:34 AM by Hibernate Tools 4.3.1

/**
 * GroupMember generated by hbm2java
 */
@XmlRootElement
public class GroupMember implements java.io.Serializable {

	private Integer id;
	private Group group;
	private User user;
	private boolean accept;
	private boolean dealtWith;

	public GroupMember() {
	}

	public GroupMember(Group group, User user, boolean accept, boolean dealtWith) {
		this.group = group;
		this.user = user;
		this.accept = accept;
		this.dealtWith = dealtWith;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@XmlTransient
	public Group getGroup() {
		return this.group;
	}

	public void setGroup(Group group) {
		this.group = group;
	}

	@XmlTransient
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public boolean isAccept() {
		return this.accept;
	}

	public void setAccept(boolean accept) {
		this.accept = accept;
	}

	public boolean isDealtWith() {
		return this.dealtWith;
	}

	public void setDealtWith(boolean dealtWith) {
		this.dealtWith = dealtWith;
	}

}
