package com.mock.fb.model;

// Generated Jun 2, 2015 9:17:34 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlTransient;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer id;
	private String name;
	private String password;
	private Set groups = new HashSet(0);
	private Set groupPosts = new HashSet(0);
	private Set friendsesForUserId = new HashSet(0);
	private Set groupMembers = new HashSet(0);
	private Set postsForPosterId = new HashSet(0);
	private Set postsForWallId = new HashSet(0);
	private Set persons = new HashSet(0);
	private Set friendsesForFriendId = new HashSet(0);

	public User() {
	}

	public User(String name, String password) {
		this.name = name;
		this.password = password;
	}

	public User(String name, String password, Set groups, Set groupPosts,
			Set friendsesForUserId, Set groupMembers, Set postsForPosterId,
			Set postsForWallId, Set persons, Set friendsesForFriendId) {
		this.name = name;
		this.password = password;
		this.groups = groups;
		this.groupPosts = groupPosts;
		this.friendsesForUserId = friendsesForUserId;
		this.groupMembers = groupMembers;
		this.postsForPosterId = postsForPosterId;
		this.postsForWallId = postsForWallId;
		this.persons = persons;
		this.friendsesForFriendId = friendsesForFriendId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@XmlTransient
	public Set getGroups() {
		return this.groups;
	}

	public void setGroups(Set groups) {
		this.groups = groups;
	}

	@XmlTransient
	public Set getGroupPosts() {
		return this.groupPosts;
	}

	public void setGroupPosts(Set groupPosts) {
		this.groupPosts = groupPosts;
	}

	@XmlTransient
	public Set getFriendsesForUserId() {
		return this.friendsesForUserId;
	}

	public void setFriendsesForUserId(Set friendsesForUserId) {
		this.friendsesForUserId = friendsesForUserId;
	}

	@XmlTransient
	public Set getGroupMembers() {
		return this.groupMembers;
	}

	public void setGroupMembers(Set groupMembers) {
		this.groupMembers = groupMembers;
	}

	@XmlTransient
	public Set getPostsForPosterId() {
		return this.postsForPosterId;
	}

	public void setPostsForPosterId(Set postsForPosterId) {
		this.postsForPosterId = postsForPosterId;
	}

	@XmlTransient
	public Set getPostsForWallId() {
		return this.postsForWallId;
	}

	public void setPostsForWallId(Set postsForWallId) {
		this.postsForWallId = postsForWallId;
	}

	@XmlTransient
	public Set getPersons() {
		return this.persons;
	}

	public void setPersons(Set persons) {
		this.persons = persons;
	}

	@XmlTransient
	public Set getFriendsesForFriendId() {
		return this.friendsesForFriendId;
	}

	public void setFriendsesForFriendId(Set friendsesForFriendId) {
		this.friendsesForFriendId = friendsesForFriendId;
	}

}
